### ISSUE TITLE
MongoDB Error

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#113]
```
Jan 05, 2018 5:47:20 AM com.mongodb.DBTCPConnector initDirectConnection
WARNING: Exception executing isMaster command on localhost/127.0.0.1:27017
java.io.EOFException
	at org.bson.io.Bits.readFully(Bits.java:48)
	at org.bson.io.Bits.readFully(Bits.java:33)
	at org.bson.io.Bits.readFully(Bits.java:28)
	at com.mongodb.Response.<init>(Response.java:40)
	at com.mongodb.DBPort.go(DBPort.java:124)
	at com.mongodb.DBPort.go(DBPort.java:88)
	at com.mongodb.DBPort.findOne(DBPort.java:143)
	at com.mongodb.DBPort.runCommand(DBPort.java:148)
	at com.mongodb.DBTCPConnector.initDirectConnection(DBTCPConnector.java:548)
	at com.mongodb.DBTCPConnector.isMongosConnection(DBTCPConnector.java:372)
	at com.mongodb.Mongo.isMongosConnection(Mongo.java:627)
	at com.mongodb.DB.wrapCommand(DB.java:294)
	at com.mongodb.DB.command(DB.java:272)
	at com.mongodb.DB.command(DB.java:256)
	at com.mongodb.DB.command(DB.java:313)
	at com.mongodb.DB.command(DB.java:211)
	at com.mongodb.DB.dropDatabase(DB.java:569)
	at net.simon987.server.GameServer.save(GameServer.java:226)
	at net.simon987.server.GameServer.tick(GameServer.java:158)
	at net.simon987.server.GameServer.run(GameServer.java:96)
	at java.base/java.lang.Thread.run(Thread.java:844)

Jan 05, 2018 5:47:20 AM com.mongodb.DBTCPConnector initDirectConnection
WARNING: Exception executing isMaster command on localhost/127.0.0.1:27017
java.io.EOFException
	at org.bson.io.Bits.readFully(Bits.java:48)
	at org.bson.io.Bits.readFully(Bits.java:33)
	at org.bson.io.Bits.readFully(Bits.java:28)
	at com.mongodb.Response.<init>(Response.java:40)
	at com.mongodb.DBPort.go(DBPort.java:124)
	at com.mongodb.DBPort.go(DBPort.java:88)
	at com.mongodb.DBPort.findOne(DBPort.java:143)
	at com.mongodb.DBPort.runCommand(DBPort.java:148)
	at com.mongodb.DBTCPConnector.initDirectConnection(DBTCPConnector.java:548)
	at com.mongodb.DBTCPConnector.checkMaster(DBTCPConnector.java:527)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:277)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:257)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:310)
	at com.mongodb.DB.command(DB.java:274)
	at com.mongodb.DB.command(DB.java:256)
	at com.mongodb.DB.command(DB.java:313)
	at com.mongodb.DB.command(DB.java:211)
	at com.mongodb.DB.dropDatabase(DB.java:569)
	at net.simon987.server.GameServer.save(GameServer.java:226)
	at net.simon987.server.GameServer.tick(GameServer.java:158)
	at net.simon987.server.GameServer.run(GameServer.java:96)
	at java.base/java.lang.Thread.run(Thread.java:844)

Jan 05, 2018 5:47:20 AM com.mongodb.DBPortPool gotError
WARNING: emptying DBPortPool to localhost/127.0.0.1:27017 b/c of error
java.io.EOFException
	at org.bson.io.Bits.readFully(Bits.java:48)
	at org.bson.io.Bits.readFully(Bits.java:33)
	at org.bson.io.Bits.readFully(Bits.java:28)
	at com.mongodb.Response.<init>(Response.java:40)
	at com.mongodb.DBPort.go(DBPort.java:124)
	at com.mongodb.DBPort.call(DBPort.java:74)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:286)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:257)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:310)
	at com.mongodb.DB.command(DB.java:274)
	at com.mongodb.DB.command(DB.java:256)
	at com.mongodb.DB.command(DB.java:313)
	at com.mongodb.DB.command(DB.java:211)
	at com.mongodb.DB.dropDatabase(DB.java:569)
	at net.simon987.server.GameServer.save(GameServer.java:226)
	at net.simon987.server.GameServer.tick(GameServer.java:158)
	at net.simon987.server.GameServer.run(GameServer.java:96)
	at java.base/java.lang.Thread.run(Thread.java:844)

Exception in thread "Thread-3" com.mongodb.MongoException$Network: can't call something : localhost/127.0.0.1:27017/mar
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:295)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:257)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:310)
	at com.mongodb.DB.command(DB.java:274)
	at com.mongodb.DB.command(DB.java:256)
	at com.mongodb.DB.command(DB.java:313)
	at com.mongodb.DB.command(DB.java:211)
	at com.mongodb.DB.dropDatabase(DB.java:569)
	at net.simon987.server.GameServer.save(GameServer.java:226)
	at net.simon987.server.GameServer.tick(GameServer.java:158)
	at net.simon987.server.GameServer.run(GameServer.java:96)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.EOFException
	at org.bson.io.Bits.readFully(Bits.java:48)
	at org.bson.io.Bits.readFully(Bits.java:33)
	at org.bson.io.Bits.readFully(Bits.java:28)
	at com.mongodb.Response.<init>(Response.java:40)
	at com.mongodb.DBPort.go(DBPort.java:124)
	at com.mongodb.DBPort.call(DBPort.java:74)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:286)
	... 11 more
```
https://github.com/simon987/Much-Assembly-Required/blob/ce0584a49fc524224efa3e91a11095197617dc94/Server/src/main/java/net/simon987/server/GameServer.java#L226

**Comment by simon987** [comment]
Made the server crash this morning, will investigate tomorrow
