### ISSUE TITLE
ConcurrentModificationException on world request

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#17]
So I let the server run unattended overnight and this happened: 

```
[11/12 23:51:14:275] [INFO] Terrain request from guest84
[11/12 23:51:14:275] [SEVERE] Trying to read a World that does not exist!
[11/12 23:51:14:275] [INFO] Generating random world
[11/12 23:51:14:275] [INFO] Generated 7 plants for World (32767,32796)
Exception in thread "Thread-3" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:939)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:893)
	at net.simon987.server.game.GameUniverse.serialise(GameUniverse.java:164)
	at net.simon987.server.GameServer.save(GameServer.java:140)
	at net.simon987.server.GameServer.tick(GameServer.java:124)
	at net.simon987.server.GameServer.run(GameServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

I'll have to check at other places where this might happen. Ideally, this this of error shouldn't make the game server crash in the future...

**Comment by simon987** [comment]
As far I know this shouldn't happen again. Uploaded the changes to the server.
