### ISSUE TITLE
Exception is thrown during assembly

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#81]
I looked through the log files and I found several cases of this exception being thrown during assembly. I will need to investigate. It does not seem to crash the server but I assume that it does not assemble entirely the uploaded contents

```
[12/31 13:06:14:842] [SEVERE] an error occurred on connection org.java_websocket.WebSocketImpl@5e52ea23: java.lang.StringIndexOutOfBoundsException: begin 0, end 2, length 1
java.lang.StringIndexOutOfBoundsException: begin 0, end 2, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3116)
	at java.base/java.lang.String.substring(String.java:1885)
	at net.simon987.server.assembly.Assembler.parseDWInstruction(Assembler.java:135)
	at net.simon987.server.assembly.Assembler.parseDWInstruction(Assembler.java:248)
	at net.simon987.server.assembly.Assembler.parseInstruction(Assembler.java:461)
	at net.simon987.server.assembly.Assembler.parseInstruction(Assembler.java:414)
	at net.simon987.server.assembly.Assembler.parse(Assembler.java:350)
	at net.simon987.server.webserver.CodeUploadHandler.handle(CodeUploadHandler.java:26)
	at net.simon987.server.webserver.MessageEventDispatcher.dispatch(MessageEventDispatcher.java:33)
```

https://github.com/simon987/Much-Assembly-Required/blob/b21e33601ed3b541eb0f4aa0854011b5e752f524/Server/src/main/java/net/simon987/server/assembly/Assembler.java#L135

**Comment by ChartreuseK** [comment]
The issue is that substring will throw an IndexOutOfBoundsException if the end position is greater than the length of the string. It's going to happen if someone writes invalid code like:
`somelabel: D 0x1000`

Either the exception needs to be caught, and null returned if it happens (probably the better way). Or the string length checked to be >= 2 before the substring function is called.
